### ISSUE TITLE
Can we use google fonts as source? 

### ISSUE THREAD

**Issue by allanesquina** [the-fountain/fountain#1]
1 - Get the css source
`https://fonts.googleapis.com/css?family=Open+Sans`

``` css
/* cyrillic-ext */
@font-face {
  font-family: 'Open Sans';
  font-style: normal;
  font-weight: 400;
  src: local('Open Sans'), local('OpenSans'), url(https://fonts.gstatic.com/s/opensans/v13/K88pR3goAWT7BTt32Z01mxJtnKITppOI_IvcXXDNrsc.woff2) format('woff2');
  unicode-range: U+0460-052F, U+20B4, U+2DE0-2DFF, U+A640-A69F;
}
...
```

2 - Get the font path:
`https://fonts.gstatic.com/s/opensans/v13/K88pR3goAWT7BTt32Z01mxJtnKITppOI_IvcXXDNrsc.woff2`

3 - Download
